export const USERS = {
  COUNT: {
    FAILURE: 'USERS.COUNT.FAILURE',
    PENDING: 'USERS.COUNT.PENDING',
    SUCCESS: 'USERS.COUNT.SUCCESS'
  },

  GET: {
    FAILURE: 'USERS.GET.FAILURE',
    PENDING: 'USERS.GET.PENDING',
    SUCCESS: 'USERS.GET.SUCCESS'
  }
}
