export const CREDENTIALS = {
  DELETE: {
    SUCCESS: 'CREDENTIALS.DELETE.SUCCESS'
  },

  POST: {
    FAILURE: 'CREDENTIALS.POST.FAILURE',
    PROPOSE: 'CREDENTIALS.POST.PROPOSE',
    SUCCESS: 'CREDENTIALS.POST.SUCCESS'
  }
}

export const LANGUAGES = {
  GET: {
    FAILURE: 'LANGUAGES.GET.FAILURE',
    SUCCESS: 'LANGUAGES.GET.SUCCESS'
  }
}

export const PROJECTS = {
  GET: {
    FAILURE: 'PROJECTS.GET.FAILURE',
    SUCCESS: 'PROJECTS.GET.SUCCESS'
  }
}

export const TYPES = {
  GET: {
    FAILURE: 'TYPES.GET.FAILURE',
    SUCCESS: 'TYPES.GET.SUCCESS'
  }
}

export const USER = {
  CREATE: {
    FAILURE: 'USER.CREATE.FAILURE',
    SUCCESS: 'USER.CREATE.SUCCESS'
  },

  DELETE: {
    FAILURE: 'USER.DELETE.FAILURE',
    SUCCESS: 'USER.DELETE.SUCCESS'
  },

  UPDATE: {
    FAILURE: 'USER.UPDATE.FAILURE',
    SUCCESS: 'USER.UPDATE.SUCCESS'
  }
}

export const USERS = {
  GET: {
    FAILURE: 'USERS.GET.FAILURE',
    SUCCESS: 'USERS.GET.SUCCESS'
  }
}
