export const CREDENTIALS = {
  DELETE: {
    SUCCESS: 'CREDENTIALS.DELETE.SUCCESS'
  },

  POST: {
    FAILURE: 'CREDENTIALS.POST.FAILURE',
    SUCCESS: 'CREDENTIALS.POST.SUCCESS'
  }
}

export const PRA = {
  DELETE: {
    ACCOUNTS: {
      FAILURE: 'PRA.DELETE.ACCOUNTS.FAILURE',
      SUCCESS: 'PRA.DELETE.ACCOUNTS.SUCCESS'
    }
  },

  GET: {
    ACCOUNTS: {
      FAILURE: 'PRA.GET.ACCOUNTS.FAILURE',
      SUCCESS: 'PRA.GET.ACCOUNTS.SUCCESS'
    },
    ALL:{
      FAILURE: 'PRA.GET.ALL.FAILURE',
      SUCCESS: 'PRA.GET.ALL.SUCCESS'
    },
    MESSAGES:{
      FAILURE: 'PRA.GET.MESSAGES.FAILURE',
      SUCCESS: 'PRA.GET.MESSAGES.SUCCESS'
    },
    NUMBERS:{
      FAILURE: 'PRA.GET.NUMBERS.FAILURE',
      SUCCESS: 'PRA.GET.NUMBERS.SUCCESS'
    },
    PLANS:{
      FAILURE: 'PRA.GET.PLANS.FAILURE',
      SUCCESS: 'PRA.GET.PLANS.SUCCESS'
    },
    PROJECTS:{
      FAILURE: 'PRA.GET.PROJECTS.FAILURE',
      SUCCESS: 'PRA.GET.PROJECTS.SUCCESS'
    }
  },

  LIST: {
    MESSAGES:{
      FAILURE: 'PRA.LIST.MESSAGES.FAILURE',
      SUCCESS: 'PRA.LIST.MESSAGES.SUCCESS'
    },
    NUMBERS:{
      FAILURE: 'PRA.LIST.NUMBERS.FAILURE',
      SUCCESS: 'PRA.LIST.NUMBERS.SUCCESS'
    },
    PLANS:{
      FAILURE: 'PRA.LIST.PLANS.FAILURE',
      SUCCESS: 'PRA.LIST.PLANS.SUCCESS'
    },
    PROJECTS:{
      FAILURE: 'PRA.LIST.PROJECTS.FAILURE',
      SUCCESS: 'PRA.LIST.PROJECTS.SUCCESS'
    },
    ROLES:{
      FAILURE: 'PRA.LIST.ROLES.FAILURE',
      SUCCESS: 'PRA.LIST.ROLES.SUCCESS'
    }
  },

  PATCH: {
    ACCOUNTS: {
      FAILURE: 'PRA.PATCH.ACCOUNTS.FAILURE',
      SUCCESS: 'PRA.PATCH.ACCOUNTS.SUCCESS'
    }
  },

  POST: {
    ACCOUNTS: {
      FAILURE: 'PRA.POST.ACCOUNTS.FAILURE',
      SUCCESS: 'PRA.POST.ACCOUNTS.SUCCESS'
    }
  }
}
